# Generated by Django 4.1.3 on 2022-11-02 04:16

from django.db import migrations, models

import slopes.utils_standalone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Slope",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
            ],
            bases=(slopes.utils_standalone.DateModel, models.Model),
        ),
    ]
