# Generated by Django 4.1.3 on 2022-11-02 05:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Slope",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
            ],
            options={
                "get_latest_by": ["created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SlopeUpdate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("effective_date", models.DateTimeField()),
                ("comment", models.CharField(max_length=2000)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("SEASON_OPENING", "SEASON_OPENING"),
                            ("SEASON_CLOSING", "SEASON_CLOSING"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("APPROXIMATE", "APPROXIMATE"),
                            ("CONFIRMED", "CONFIRMED"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "slope",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="slopes.slope"
                    ),
                ),
            ],
            options={
                "get_latest_by": ["created_at"],
                "abstract": False,
            },
        ),
    ]
