# Generated by Django 4.1.3 on 2022-11-02 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("slopes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="slope",
            name="description",
            field=models.CharField(default="", max_length=2000),
            preserve_default=False,
        ),
    ]
