# Generated by Django 4.1.3 on 2022-11-02 04:33

import django.db.models.deletion
from django.db import migrations, models

import slopes.utils_standalone


class Migration(migrations.Migration):

    dependencies = [
        ("slopes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SlopeUpdate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("season_opening", "SEASON_OPENING"),
                            ("season_closing", "SEASON_CLOSING"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("approximate", "APPROXIMATE"),
                            ("confirmed", "CONFIRMED"),
                        ],
                        max_length=50,
                    ),
                ),
                ("effective_date", models.DateTimeField()),
                (
                    "slope",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="slopes.slope"
                    ),
                ),
            ],
            bases=(slopes.utils_standalone.DateModel, models.Model),
        ),
    ]
