# Generated by Django 4.1.3 on 2022-11-02 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("slopes", "0002_slopeupdate"),
    ]

    operations = [
        migrations.AddField(
            model_name="slopeupdate",
            name="comment",
            field=models.CharField(default="none", max_length=2000),
            preserve_default=False,
        ),
    ]
